// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLSave is an autogenerated mock type for the URLSave type
type URLSave struct {
	mock.Mock
}

// SaveURL provides a mock function with given fields: urlToSave, alias
func (_m *URLSave) SaveURL(urlToSave string, alias string) (int64, error) {
	ret := _m.Called(urlToSave, alias)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return rf(urlToSave, alias)
	}
	if rf, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = rf(urlToSave, alias)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(urlToSave, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewURLSave interface {
	mock.TestingT
	Cleanup(func())
}

// NewURLSave creates a new instance of URLSave. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewURLSave(t mockConstructorTestingTNewURLSave) *URLSave {
	mock := &URLSave{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
